version: "3.9"

services:
  bot:
    build: .
    container_name: OrVD
    restart: always
    env_file:
      - .env
    volumes:
      - ./files:/app/files  # Подключаем папку с файлами
      - ./db.sqlite3:/app/db.sqlite3  # Подключаем БД
    ports:
      - "8000:8000"